import cv2
import enum
import numpy as np
import tkinter as tk
from typing import Any

__version__: str

class BorderStyle(enum.Enum):
    Raised: str
    Sunken: str
    Groove: str
    Ridge: str
    Solid: str
    Flat: str

class ImageMode(enum.IntEnum):
    Normal: int
    CenterImage: int
    StretchImage: int
    AutoSize: int
    Zoom: int

class PictureBox(tk.Label):
    def __init__(self, parent: Any, width: int, height: int): ...
    @property
    def border_style(self) -> str | BorderStyle: ...
    @border_style.setter
    def border_style(self, style: str | BorderStyle) -> None: ...
    @property
    def image_mode(self) -> int | ImageMode: ...
    @image_mode.setter
    def image_mode(self, mode: int | ImageMode) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    def clear(self) -> None: ...
    def display(self, image: np.ndarray | cv2.Mat) -> bool: ...
    def load(self, filename: str) -> bool: ...
    def save(self, filename: str) -> bool: ...
    def set_background(self, color: str | tuple[int, int, int] | tuple[float, float, float]) -> None: ...
